'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frm_RptMovimientoAlmacen

  '''<summary>
  '''Head1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

  '''<summary>
  '''frmData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents frmData As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''ScriptManager1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''panContenido control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents panContenido As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''TxtFechaIni control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtFechaIni As Global.Infragistics.Web.UI.EditorControls.WebDatePicker

  '''<summary>
  '''btnBuscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''TxtFechaFin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtFechaFin As Global.Infragistics.Web.UI.EditorControls.WebDatePicker

  '''<summary>
  '''ddlEstado control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlEstado As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''txtNumDocAlmacen control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtNumDocAlmacen As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtSeriePedidoAlmacen control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSeriePedidoAlmacen As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtNumPedidoAlmacen control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtNumPedidoAlmacen As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtUrl control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtUrl As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblMsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
