'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class PLA20016

    '''<summary>
    '''frmHESolicitud control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmHESolicitud As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdnCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCodigo As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnAccion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAccion As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtAnio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAnio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlMes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnProcesar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnProcesar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''dgdDetalle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgdDetalle As Global.System.Web.UI.WebControls.DataGrid

    '''<summary>
    '''HDN2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDN2 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDN1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDN1 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDN4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDN4 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDN3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDN3 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDN5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDN5 As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''HDN6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDN6 As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
