'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frm_ConsultaEstructuraNM

  '''<summary>
  '''frmConsultaEstructura control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents frmConsultaEstructura As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''ScriptManager1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''panContenido control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents panContenido As Global.System.Web.UI.UpdatePanel

  '''<summary>
  '''lblTtulo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTtulo As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtCodigo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtCodigo As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''btnConsultar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnConsultar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''txtDescripcion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtDescripcion As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblError control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblError As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''dgDatos control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dgDatos As Global.System.Web.UI.WebControls.DataGrid
End Class
