'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frm_RegistrarOrdenServicio

    '''<summary>
    '''frmRequisicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmRequisicion As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''hdnCCDestino control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCCDestino As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''hdnOrdServicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnOrdServicio As Global.System.Web.UI.HtmlControls.HtmlInputHidden

    '''<summary>
    '''txtFecIns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFecIns As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlMotivoRequisicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlMotivoRequisicion As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rdPresupuestado_SI control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdPresupuestado_SI As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdPresupuestado_NO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdPresupuestado_NO As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdTipoInterna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdTipoInterna As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''rdTipoExterna control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdTipoExterna As Global.System.Web.UI.WebControls.RadioButton

    '''<summary>
    '''lblMensaje control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMensaje As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMotivoRechazo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMotivoRechazo As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSolicitarPRE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSolicitarPRE As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnListaAdjuntos control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnListaAdjuntos As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''HDNDesCtaGasto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents HDNDesCtaGasto As Global.System.Web.UI.HtmlControls.HtmlInputHidden
End Class
