'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmFichaProveedor

  '''<summary>
  '''Head1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

  '''<summary>
  '''frmData control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents frmData As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''ScriptManager1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''panActualizaO control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents panActualizaO As Global.System.Web.UI.WebControls.Panel

  '''<summary>
  '''lblNroOrdeServicio control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNroOrdeServicio As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''txtNroRequisicion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtNroRequisicion As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblNombreProveedor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNombreProveedor As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblRuc control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblRuc As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblNombreContacto control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblNombreContacto As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblEmail control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEmail As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblTelefonoContacto control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblTelefonoContacto As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblEstado control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblEstado As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblFecha control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblFecha As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblUsuario control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblUsuario As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblObservaciones control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblObservaciones As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''rdTiposervicio1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rdTiposervicio1 As Global.System.Web.UI.WebControls.RadioButton

  '''<summary>
  '''rdTiposervicio2 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents rdTiposervicio2 As Global.System.Web.UI.WebControls.RadioButton

  '''<summary>
  '''TxtCodigoTrabajador control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCodigoTrabajador As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtNombreTrabajador control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtNombreTrabajador As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''wdpFechaInicio control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents wdpFechaInicio As Global.Infragistics.Web.UI.EditorControls.WebDatePicker

  '''<summary>
  '''wdpFechaFin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents wdpFechaFin As Global.Infragistics.Web.UI.EditorControls.WebDatePicker

  '''<summary>
  '''TxtTiempoOfertado control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtTiempoOfertado As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtTiempoReal control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtTiempoReal As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''wdgDetalle control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents wdgDetalle As Global.Infragistics.Web.UI.GridControls.WebDataGrid

  '''<summary>
  '''cmbTrabajo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmbTrabajo As Global.Infragistics.Web.UI.GridControls.DropDownProvider

  '''<summary>
  '''cmbMateriales control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmbMateriales As Global.Infragistics.Web.UI.GridControls.DropDownProvider

  '''<summary>
  '''cmbCalidad control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmbCalidad As Global.Infragistics.Web.UI.GridControls.DropDownProvider

  '''<summary>
  '''cmbNormasSeguridad control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmbNormasSeguridad As Global.Infragistics.Web.UI.GridControls.DropDownProvider

  '''<summary>
  '''TxtObservaciones control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtObservaciones As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''cmbExperiencia control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmbExperiencia As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''cmbConformidad control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmbConformidad As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''imgGrabarFicha control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents imgGrabarFicha As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''imgCancelar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents imgCancelar As Global.System.Web.UI.WebControls.ImageButton

  '''<summary>
  '''btnSolicitaAprobacion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnSolicitaAprobacion As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''btnAdjuntos control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnAdjuntos As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''TxtAprobacion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtAprobacion As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''TxtDescripcion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtDescripcion As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblMsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
End Class
