'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmFormatoCambioPuesto

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''imgbtnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnVolver As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtFecInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFecInicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfIdFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdFormato As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtNombres control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNombres As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCodigo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCodigo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPuestoAct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPuestoAct As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfPuestoA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPuestoA As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtPuestoProm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPuestoProm As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSolicitante control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSolicitante As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''hdfCodPuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodPuesto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdnCargarNuevoPuesto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCargarNuevoPuesto As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtArea As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hdfArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfArea As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtFecIni control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFecIni As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtCalendar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtCalendar2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''txtSuper control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSuper As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnJefe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnJefe As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''hdfCodJefe control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodJefe As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtCompa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCompa As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnCompa control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCompa As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''hdfCodTrab control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfCodTrab As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtTiempo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtTiempo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''gvEval1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEval1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtValorFooter1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorFooter1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtValorTot1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorTot1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''gvEval2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvEval2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtValorFooter2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorFooter2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtValorTot2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtValorTot2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtOpinion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtOpinion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvFirmas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFirmas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSolicitar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSolicitar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAprobar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnular As Global.System.Web.UI.WebControls.Button
End Class
