'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmListadoPedidosDistribucion

    '''<summary>
    '''Head1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Head1 As Global.System.Web.UI.HtmlControls.HtmlHead

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''ScriptManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''uplContenido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents uplContenido As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''combobox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents combobox As Global.Infragistics.Web.UI.ListControls.WebDropDown

    '''<summary>
    '''btnBuscar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStock control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStock As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''up_Load control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents up_Load As Global.System.Web.UI.UpdateProgress

    '''<summary>
    '''BtnLimpiarProgramados control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnLimpiarProgramados As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnConcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnConcluir As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''BtnEnviar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEnviar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''DivTablaPrincipal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivTablaPrincipal As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblTituloTotalDistribSinProg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloTotalDistribSinProg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTotalDistribSinProg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTotalDistribSinProg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''IbtnRefrescarSvsP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IbtnRefrescarSvsP As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblTituloStockvsPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloStockvsPedido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblStockvsPedido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStockvsPedido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblTituloCodigoArt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblTituloCodigoArt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblCodigoArt control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCodigoArt As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''grvListArtDist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents grvListArtDist As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''EsMostrar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents EsMostrar As Global.System.Web.UI.HtmlControls.HtmlTableRow

    '''<summary>
    '''lblCantidad control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCantidad As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblSumaDistri control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSumaDistri As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblPedidoConcluido control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPedidoConcluido As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DivSinConcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivSinConcluir As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblSinConcluir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSinConcluir As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''DistTotal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DistTotal As Global.System.Web.UI.HtmlControls.HtmlGenericControl
End Class
