'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmListaOS

  '''<summary>
  '''frmListadoOS control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents frmListadoOS As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''ScriptManager1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ScriptManager1 As Global.System.Web.UI.ScriptManager

  '''<summary>
  '''cmbOpcion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents cmbOpcion As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btnBuscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnBuscar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''TxtCodigoProveedor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents TxtCodigoProveedor As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtNombreProveedor control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtNombreProveedor As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''wdpFecIni control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents wdpFecIni As Global.Infragistics.Web.UI.EditorControls.WebDatePicker

  '''<summary>
  '''wdpFecFin control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents wdpFecFin As Global.Infragistics.Web.UI.EditorControls.WebDatePicker

  '''<summary>
  '''txtSerie control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtSerie As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtNumOrden control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtNumOrden As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''lblMsg control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''lblContador control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents lblContador As Global.System.Web.UI.WebControls.Label

  '''<summary>
  '''dtgLista control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents dtgLista As Global.System.Web.UI.WebControls.DataGrid
End Class
