'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class frmListadoCambioProceso

    '''<summary>
    '''form1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents form1 As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''imgbtnVolver control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgbtnVolver As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''ddlArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlArea As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnpurb control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnpurb As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''hdfIdGenFormato control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfIdGenFormato As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtMaquina control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMaquina As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtResponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtResponsable As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnResponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnResponsable As Global.System.Web.UI.HtmlControls.HtmlInputButton

    '''<summary>
    '''hdnResponsable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnResponsable As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''txtFecInicio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFecInicio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtObjCambio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtObjCambio As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvBloque1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvBloque1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''txtConsRiesgo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConsRiesgo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''script1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents script1 As Global.System.Web.UI.ScriptManager

    '''<summary>
    '''ibtAgregarProd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtAgregarProd As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''hdfPanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPanel2 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''hdfPanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdfPanel3 As Global.System.Web.UI.WebControls.HiddenField

    '''<summary>
    '''gvProduc1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProduc1 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlProduccion2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProduccion2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ibtMenos2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtMenos2 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''gvProduc2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProduc2 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''pnlProduccion3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pnlProduccion3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''ibtMenos3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtMenos3 As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''gvProduc3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvProduc3 As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''fluAdjuntarFicha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fluAdjuntarFicha As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''ibtDescargarfichas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtDescargarfichas As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''lblficha control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblficha As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtFecConc control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFecConc As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ibtCalendar2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ibtCalendar2 As Global.System.Web.UI.HtmlControls.HtmlImage

    '''<summary>
    '''txtDescConcl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDescConcl As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''gvFirmas control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gvFirmas As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''btnGuardar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnGuardar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSolicitar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSolicitar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAprobar control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAprobar As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAnular control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAnular As Global.System.Web.UI.WebControls.Button
End Class
