'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LOG20012

  '''<summary>
  '''frmRequisicion control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents frmRequisicion As Global.System.Web.UI.HtmlControls.HtmlForm

  '''<summary>
  '''ddlalmtransf control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents ddlalmtransf As Global.System.Web.UI.WebControls.DropDownList

  '''<summary>
  '''btnbuscar control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents btnbuscar As Global.System.Web.UI.WebControls.Button

  '''<summary>
  '''txtcodarticulo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtcodarticulo As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''txtdesarticulo control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents txtdesarticulo As Global.System.Web.UI.WebControls.TextBox

  '''<summary>
  '''DataGrid1 control.
  '''</summary>
  '''<remarks>
  '''Auto-generated field.
  '''To modify move field declaration from designer file to code-behind file.
  '''</remarks>
  Protected WithEvents DataGrid1 As Global.System.Web.UI.WebControls.DataGrid
End Class
