'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class LOG20012_P

    '''<summary>
    '''frmRequisicion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents frmRequisicion As Global.System.Web.UI.HtmlControls.HtmlForm

    '''<summary>
    '''txtcodarticulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcodarticulo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtdesarticulo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtdesarticulo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''ddlcodigobarra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlcodigobarra As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtUbicacion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtUbicacion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtcant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcant As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnimprimir control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnimprimir As Global.System.Web.UI.WebControls.Button
End Class
